version: '3'
services:
  cipher:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    
    volumes:
      - .:/app
      - /app/node_modules