version: '3'
services:
  cipher:
    build: 
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000" # To use without nginx
    env_file:
      - ./.env
    
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # To http
      - "443:443" # To https
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cipher